#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	# We are running on linux, need to do users properly
	docker run \
		`# Run interactively` \
		-it \
		`# Mount entire repository to /vc to compile from` \
		-v /$PWD:/vc:cached \
		`# Run as current user so builds have correct ownership` \
		--user $(id -u):$(id -g) \
		`# Run vc image generated by setup.sh` \
		vc
else
	# We are running on windows / mac
	# docker desktop makes everything root as per:
	# https://github.com/docker/for-mac/issues/6734
	docker run \
		`# Run interactively` \
		-it \
		`# Mount entire repository to /vc to compile from` \
		-v /$PWD:/vc:cached \
		`# Run vc image generated by setup.sh` \
		vc
fi
