#!/usr/bin/env bash

docker run \
	`# Run interactively` \
	-it \
	`# Mount entire repository to /vc to compile from` \
	-v /$PWD:/vc:cached \
	`# Run as current user so builds have correct ownership` \
	--user $(id -u):$(id -g) \
	`# Run vc image generated by setup.sh` \
	vc
